application: web-caesar
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

#added per advice from https://sites.google.com/site/usfcomputerscience/loading-images-and-css-in-appengine
- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets
###

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
